Invoke-Expression "C:\Progra~1\CPUID\CPU-Z\cpuz.exe"
Invoke-Expression "C:\Progra~1\CPUID\CPU-Z\cpuz.exe"
Invoke-Expression "C:\Progra~1\CPUID\CPU-Z\cpuz.exe"
Invoke-Expression "C:\Progra~1\CPUID\CPU-Z\cpuz.exe"
Invoke-Expression "C:\Users\nispoe\AppData\Local\Programs\BenchMate\BenchMate.exe"
Invoke-Expression "& 'C:\Program Files (x86)\FinalWire\AIDA64 Extreme\aida64.exe'"